### ISSUE TITLE
Remove autobind-decorator

### ISSUE THREAD

**Issue by jaulz** [kjanoudi/joiful-react-forms#26]
Please remove the autobind-decorator from the dependencies. Instead simply use the following in the constructor:
`
this.getStateFromProps = this.getStateFromProps.bind(this)
`

If you don't like this please set it at least as a dependency and not as a dev dependency. Currently it triggers an exception and requires a manual installation of autobind-decorator.

**Comment by rawgroundbeef** [comment]
I agree. Do you mind submitting a PR?

**Comment by jaulz** [comment]
Great!
Please see: https://github.com/kjanoudi/joiful-react-forms/pull/27

**Comment by rawgroundbeef** [comment]
On second thought, you shouldn't need `autobind-decorator` as a dependency.. (I could be wrong)

**Comment by rawgroundbeef** [comment]
@kjanoudi thoughts?

**Comment by jaulz** [comment]
At least the dist version on npm contains this:

```
var _autobindDecorator = require('autobind-decorator');
```

This is obviously not installed because it is a dev dependency.

**Comment by rawgroundbeef** [comment]
Yeah, you're totally right.
